
pub fn bug(name: impl AsRef<str>) -> usize {
    let name = name.as_ref().to_lowercase();

    match BUGS.iter().position(|&other| other == name) {
        Some(index) => index,
        _ => panic!("bug '{}' has no id yet", name),
    }
}

pub fn fish(name: impl AsRef<str>) -> usize {
    let name = name.as_ref().to_lowercase();

    match FISH.iter().position(|&other| other == name) {
        Some(index) => index,
        _ => panic!("fish '{}' has no id yet", name),
    }
}

pub fn fossil(name: impl AsRef<str>) -> usize {
    let name = name.as_ref().to_lowercase();

    match FOSSILS.iter().position(|&other| other == name) {
        Some(index) => index,
        _ => panic!("fossil '{}' has no id yet", name),
    }
}

const BUGS: &[&str] = &[
    "common butterfly",
    "yellow butterfly",
    "tiger butterfly",
    "peacock butterfly",
    "common bluebottle",
    "paper kite butterfly",
    "great purple emperor",
    "monarch butterfly",
    "emperor butterfly",
    "agrias butterfly",
    "rajah brooke's birdwing",
    "queen alexandra's birdwing",
    "moth",
    "atlas moth",
    "madagascan sunset moth",
    "long locust",
    "migratory locust",
    "rice grasshopper",
    "grasshopper",
    "cricket",
    "bell cricket",
    "mantis",
    "orchid mantis",
    "honeybee",
    "wasp",
    "brown cicada",
    "robust cicada",
    "giant cicada",
    "walker cicada",
    "evening cicada",
    "cicada shell",
    "red dragonfly",
    "darner dragonfly",
    "banded dragonfly",
    "damselfly",
    "firefly",
    "mole cricket",
    "pondskater",
    "diving beetle",
    "giant water bug",
    "stinkbug",
    "man-faced stink bug",
    "ladybug",
    "tiger beetle",
    "jewel beetle",
    "violin beetle",
    "citrus long-horned beetle",
    "rosalia batesi beetle",
    "blue weevil beetle",
    "dung beetle",
    "earth-boring dung beetle",
    "scarab beetle",
    "drone beetle",
    "goliath beetle",
    "saw stag",
    "miyama stag",
    "giant stag",
    "rainbow stag",
    "cyclommatus stag",
    "golden stag",
    "giraffe stag",
    "horned dynastid",
    "horned atlas",
    "horned elephant",
    "horned hercules",
    "walking stick",
    "walking leaf",
    "bagworm",
    "ant",
    "hermit crab",
    "wharf roach",
    "fly",
    "mosquito",
    "flea",
    "snail",
    "pill bug",
    "centipede",
    "spider",
    "tarantula",
    "scorpion",
];

const FISH: &[&str] = &[
    "bitterling",
    "pale chub",
    "crucian carp",
    "dace",
    "carp",
    "koi",
    "goldfish",
    "pop-eyed goldfish",
    "ranchu goldfish",
    "killifish",
    "crawfish",
    "soft-shelled turtle",
    "snapping turtle",
    "tadpole",
    "frog",
    "freshwater goby",
    "loach",
    "catfish",
    "giant snakehead",
    "bluegill",
    "yellow perch",
    "black bass",
    "tilapia",
    "pike",
    "pond smelt",
    "sweetfish",
    "cherry salmon",
    "char",
    "golden trout",
    "stringfish",
    "salmon",
    "king salmon",
    "mitten crab",
    "guppy",
    "nibble fish",
    "angelfish",
    "betta",
    "neon tetra",
    "rainbowfish",
    "piranha",
    "arowana",
    "dorado",
    "gar",
    "arapaima",
    "saddled bichir",
    "sturgeon",
    "sea butterfly",
    "sea horse",
    "clown fish",
    "surgeonfish",
    "butterfly fish",
    "napoleonfish",
    "zebra turkeyfish",
    "blowfish",
    "puffer fish",
    "anchovy",
    "horse mackerel",
    "barred knifejaw",
    "sea bass",
    "red snapper",
    "dab",
    "olive flounder",
    "squid",
    "moray eel",
    "ribbon eel",
    "tuna",
    "blue marlin",
    "giant trevally",
    "mahi-mahi",
    "ocean sunfish",
    "ray",
    "saw shark",
    "hammerhead shark",
    "great white shark",
    "whale shark",
    "suckerfish",
    "football fish",
    "oarfish",
    "barreleye",
    "coelacanth",
];

const FOSSILS: &[&str] = &[
    "acanthostega",
    "amber",
    "ammonite",
    "anomalocaris",
    "archaeopteryx",
    "australopith",
    "coprolite",
    "dinosaur track",
    "dunkleosteus",
    "eusthenopteron",
    "juramaia",
    "myllokunmingia",
    "shark-tooth pattern",
    "trilobite",
    "ankylo skull",
    "ankylo torso",
    "ankylo tail",
    "archelon skull",
    "archelon tail",
    "brachio skull",
    "brachio chest",
    "brachio pelvis",
    "brachio tail",
    "deinony torso",
    "deinony tail",
    "dimetrodon skull",
    "dimetrodon torso",
    "diplo skull",
    "diplo neck",
    "diplo chest",
    "diplo pelvis",
    "diplo tail",
    "diplo tail tip",
    "iguanodon skull",
    "iguanodon torso",
    "iguanodon tail",
    "mammoth skull",
    "mammoth torso",
    "megacero skull",
    "megacero torso",
    "megacero tail",
    "left megalo side",
    "right megalo side",
    "ophthalmo skull",
    "ophthalmo torso",
    "pachysaurus skull",
    "pachysaurus tail",
    "parasaur skull",
    "parasaur torso",
    "parasaur tail",
    "plesio skull",
    "plesio tail",
    "plesio body",
    "right ptera wing",
    "ptera body",
    "left ptera wing",
    "right quetzal wing",
    "quetzal torso",
    "left quetzal wing",
    "sabertooth skull",
    "sabertooth tail",
    "spino skull",
    "spino torso",
    "spino tail",
    "stego skull",
    "stego torso",
    "stego tail",
    "tricera skull",
    "tricera torso",
    "tricera tail",
    "t. rex skull",
    "t. rex torso",
    "t. rex tail",
];
