
pub fn bug(name: impl AsRef<str>) -> usize {
    let name = name.as_ref().to_lowercase();

    match BUGS.iter().position(|&other| other == name) {
        Some(index) => index,
        _ => panic!("bug '{}' has no id yet", name),
    }
}

pub fn fish(name: impl AsRef<str>) -> usize {
    let name = name.as_ref().to_lowercase();

    match FISH.iter().position(|&other| other == name) {
        Some(index) => index,
        _ => panic!("fish '{}' has no id yet", name),
    }
}

pub fn fossil(name: impl AsRef<str>) -> usize {
    let name = name.as_ref().to_lowercase();

    match FOSSILS.iter().position(|&other| other == name) {
        Some(index) => index,
        _ => panic!("fossil '{}' has no id yet", name),
    }
}

pub fn flower(name: impl AsRef<str>) -> usize {
    let name = name.as_ref().to_lowercase();

    match FLOWERS.iter().position(|&other| other == name) {
        Some(index) => index,
        _ => panic!("flower '{}' has no id yet", name),
    }
}

pub fn art(name: impl AsRef<str>) -> usize {
    let name = name.as_ref().to_lowercase();

    match ART.iter().position(|&other| other == name) {
        Some(index) => index,
        _ => panic!("art '{}' has no id yet", name),
    }
}

pub fn villager(name: impl AsRef<str>) -> usize {
    let name = name.as_ref().to_lowercase();

    match VILLAGERS.iter().position(|&other| other == name) {
        Some(index) => index,
        _ => panic!("villager '{}' has no id yet", name),
    }
}

const BUGS: &[&str] = &[
    "common butterfly",
    "yellow butterfly",
    "tiger butterfly",
    "peacock butterfly",
    "common bluebottle",
    "paper kite butterfly",
    "great purple emperor",
    "monarch butterfly",
    "emperor butterfly",
    "agrias butterfly",
    "rajah brooke's birdwing",
    "queen alexandra's birdwing",
    "moth",
    "atlas moth",
    "madagascan sunset moth",
    "long locust",
    "migratory locust",
    "rice grasshopper",
    "grasshopper",
    "cricket",
    "bell cricket",
    "mantis",
    "orchid mantis",
    "honeybee",
    "wasp",
    "brown cicada",
    "robust cicada",
    "giant cicada",
    "walker cicada",
    "evening cicada",
    "cicada shell",
    "red dragonfly",
    "darner dragonfly",
    "banded dragonfly",
    "damselfly",
    "firefly",
    "mole cricket",
    "pondskater",
    "diving beetle",
    "giant water bug",
    "stinkbug",
    "man-faced stink bug",
    "ladybug",
    "tiger beetle",
    "jewel beetle",
    "violin beetle",
    "citrus long-horned beetle",
    "rosalia batesi beetle",
    "blue weevil beetle",
    "dung beetle",
    "earth-boring dung beetle",
    "scarab beetle",
    "drone beetle",
    "goliath beetle",
    "saw stag",
    "miyama stag",
    "giant stag",
    "rainbow stag",
    "cyclommatus stag",
    "golden stag",
    "giraffe stag",
    "horned dynastid",
    "horned atlas",
    "horned elephant",
    "horned hercules",
    "walking stick",
    "walking leaf",
    "bagworm",
    "ant",
    "hermit crab",
    "wharf roach",
    "fly",
    "mosquito",
    "flea",
    "snail",
    "pill bug",
    "centipede",
    "spider",
    "tarantula",
    "scorpion",
];

const FISH: &[&str] = &[
    "bitterling",
    "pale chub",
    "crucian carp",
    "dace",
    "carp",
    "koi",
    "goldfish",
    "pop-eyed goldfish",
    "ranchu goldfish",
    "killifish",
    "crawfish",
    "soft-shelled turtle",
    "snapping turtle",
    "tadpole",
    "frog",
    "freshwater goby",
    "loach",
    "catfish",
    "giant snakehead",
    "bluegill",
    "yellow perch",
    "black bass",
    "tilapia",
    "pike",
    "pond smelt",
    "sweetfish",
    "cherry salmon",
    "char",
    "golden trout",
    "stringfish",
    "salmon",
    "king salmon",
    "mitten crab",
    "guppy",
    "nibble fish",
    "angelfish",
    "betta",
    "neon tetra",
    "rainbowfish",
    "piranha",
    "arowana",
    "dorado",
    "gar",
    "arapaima",
    "saddled bichir",
    "sturgeon",
    "sea butterfly",
    "sea horse",
    "clown fish",
    "surgeonfish",
    "butterfly fish",
    "napoleonfish",
    "zebra turkeyfish",
    "blowfish",
    "puffer fish",
    "anchovy",
    "horse mackerel",
    "barred knifejaw",
    "sea bass",
    "red snapper",
    "dab",
    "olive flounder",
    "squid",
    "moray eel",
    "ribbon eel",
    "tuna",
    "blue marlin",
    "giant trevally",
    "mahi-mahi",
    "ocean sunfish",
    "ray",
    "saw shark",
    "hammerhead shark",
    "great white shark",
    "whale shark",
    "suckerfish",
    "football fish",
    "oarfish",
    "barreleye",
    "coelacanth",
];

const FOSSILS: &[&str] = &[
    "acanthostega",
    "amber",
    "ammonite",
    "anomalocaris",
    "archaeopteryx",
    "australopith",
    "coprolite",
    "dinosaur track",
    "dunkleosteus",
    "eusthenopteron",
    "juramaia",
    "myllokunmingia",
    "shark-tooth pattern",
    "trilobite",
    "ankylo skull",
    "ankylo torso",
    "ankylo tail",
    "archelon skull",
    "archelon tail",
    "brachio skull",
    "brachio chest",
    "brachio pelvis",
    "brachio tail",
    "deinony torso",
    "deinony tail",
    "dimetrodon skull",
    "dimetrodon torso",
    "diplo skull",
    "diplo neck",
    "diplo chest",
    "diplo pelvis",
    "diplo tail",
    "diplo tail tip",
    "iguanodon skull",
    "iguanodon torso",
    "iguanodon tail",
    "mammoth skull",
    "mammoth torso",
    "megacero skull",
    "megacero torso",
    "megacero tail",
    "left megalo side",
    "right megalo side",
    "ophthalmo skull",
    "ophthalmo torso",
    "pachysaurus skull",
    "pachysaurus tail",
    "parasaur skull",
    "parasaur torso",
    "parasaur tail",
    "plesio skull",
    "plesio tail",
    "plesio body",
    "right ptera wing",
    "ptera body",
    "left ptera wing",
    "right quetzal wing",
    "quetzal torso",
    "left quetzal wing",
    "sabertooth skull",
    "sabertooth tail",
    "spino skull",
    "spino torso",
    "spino tail",
    "stego skull",
    "stego torso",
    "stego tail",
    "tricera skull",
    "tricera torso",
    "tricera tail",
    "t. rex skull",
    "t. rex torso",
    "t. rex tail",
];


const FLOWERS: &[&str] = &[
    "red cosmos",
    "white cosmos",
    "yellow cosmos",
    "pink cosmos",
    "orange cosmos",
    "black cosmos",
    "white tulips",
    "red tulips",
    "yellow tulips",
    "pink tulips",
    "orange tulips",
    "purple tulips",
    "black tulips",
    "yellow pansies",
    "red pansies",
    "white pansies",
    "orange pansies",
    "purple pansies",
    "blue pansies",
    "white roses",
    "red roses",
    "yellow roses",
    "pink roses",
    "orange roses",
    "purple roses",
    "black roses",
    "blue roses",
    "gold roses",
    "white lilies",
    "red lilies",
    "yellow lilies",
    "pink lilies",
    "orange lilies",
    "black lilies",
    "white windflowers",
    "orange windflowers",
    "red windflowers",
    "blue windflowers",
    "pink windflowers",
    "purple windflowers",
    "white hyacinths",
    "yellow hyacinths",
    "red hyacinths",
    "pink hyacinths",
    "orange hyacinths",
    "blue hyacinths",
    "purple hyacinths",
    "white mums",
    "yellow mums",
    "red mums",
    "purple mums",
    "pink mums",
    "green mums",
];

const ART: &[&str] = &[
    "robust statue",
    "rock-head statue",
    "beautiful statue",
    "valiant statue",
    "gallant statue",
    "mystic statue",
    "informative statue",
    "warrior statue",
    "tremendous statue",
    "ancient statue",
    "motherly statue",
    "familiar statue",
    "great statue",
    "quaint painting",
    "graceful painting",
    "famous painting",
    "detailed painting",
    "basic painting",
    "serene painting",
    "amazing painting",
    "solemn painting",
    "scary painting",
    "jolly painting",
    "wistful painting",
    "moving painting",
    "wild painting left half",
    "wild painting right half",
    "scenic painting",
    "academic painting",
    "common painting",
    "flowery painting",
    "twinkling painting",
    "nice painting",
    "moody painting",
    "glowing painting",
    "perfect painting",
    "mysterious painting",
    "calm painting",
    "proper painting",
    "sinking painting",
    "worthy painting",
    "warm painting",
    "dynamic painting",
];

const VILLAGERS: &[&str] = &[
    "amelia",
    "pierce",
    "apollo",
    "frank",
    "buzz",
    "sterling",
    "keaton",
    "celia",
    "avery",
    "deli",
    "tammi",
    "monty",
    "nana",
    "flip",
    "simon",
    "elise",
    "shari",
    "anabelle",
    "annalisa",
    "snooty",
    "pango",
    "olaf",
    "antonio",
    "cyrano",
    "beardo",
    "chow",
    "megan",
    "groucho",
    "grizzly",
    "klaus",
    "ike",
    "curt",
    "tutu",
    "nate",
    "paula",
    "pinky",
    "charlise",
    "teddy",
    "ursala",
    "filbert",
    "sally",
    "cally",
    "marshal",
    "agent s",
    "blaire",
    "nibbles",
    "sylvana",
    "mint",
    "hazel",
    "tasha",
    "pecan",
    "peanut",
    "caroline",
    "ricky",
    "static",
    "sheldon",
    "poppy",
    "axel",
    "dizzy",
    "big top",
    "tia",
    "ellie",
    "margie",
    "eloise",
    "opal",
    "paolo",
    "cyd",
    "tucker",
    "bill",
    "pate",
    "pompom",
    "derwin",
    "drake",
    "gloria",
    "scoot",
    "joey",
    "mallary",
    "molly",
    "deena",
    "ketchup",
    "freckles",
    "quillson",
    "maelle",
    "miranda",
    "weber",
    "croque",
    "drift",
    "diva",
    "henry",
    "frobert",
    "cousteau",
    "jambette",
    "jeremiah",
    "huck",
    "lily",
    "puddles",
    "tad",
    "prince",
    "ribbot",
    "raddle",
    "camofrog",
    "gigi",
    "wart jr.",
    "cesar",
    "boyd",
    "hans",
    "rocket",
    "al",
    "boone",
    "violet",
    "louie",
    "peewee",
    "flurry",
    "clay",
    "graham",
    "hamlet",
    "hamphrey",
    "apple",
    "rodney",
    "soleil",
    "genji",
    "chrissy",
    "claude",
    "dotty",
    "gabi",
    "gaston",
    "doc",
    "bonbon",
    "carmen",
    "cole",
    "coco",
    "pippy",
    "francine",
    "tiffany",
    "bunnie",
    "mira",
    "o'hare",
    "snake",
    "hopkins",
    "ruby",
    "benedict",
    "broffina",
    "ava",
    "ken",
    "becky",
    "goose",
    "plucky",
    "knox",
    "egbert",
    "maddie",
    "bea",
    "cherry",
    "goldie",
    "daisy",
    "walker",
    "butch",
    "portia",
    "biskit",
    "marcel",
    "cookie",
    "bones",
    "shep",
    "lucky",
    "benjamin",
    "mac",
    "astrid",
    "carrie",
    "kitt",
    "mathilda",
    "marcie",
    "rooney",
    "walt",
    "sylvia",
    "olivia",
    "lolly",
    "purrl",
    "raymond",
    "rudy",
    "katt",
    "bob",
    "punchy",
    "kabuki",
    "kitty",
    "kiki",
    "ankha",
    "mitzi",
    "felicity",
    "merry",
    "monique",
    "kid cat",
    "rosie",
    "stinky",
    "tangy",
    "tom",
    "moe",
    "tabby",
    "canberra",
    "gonzo",
    "alice",
    "melba",
    "ozzie",
    "lyman",
    "sydney",
    "eugene",
    "yuka",
    "alli",
    "drago",
    "del",
    "alfonso",
    "gayle",
    "sly",
    "boots",
    "tipper",
    "angus",
    "coach",
    "stu",
    "naomi",
    "vic",
    "t-bone",
    "norma",
    "patty",
    "rodeo",
    "bud",
    "leopold",
    "rory",
    "elvis",
    "mott",
    "lionel",
    "rex",
    "chadder",
    "dora",
    "anicotti",
    "broccolo",
    "greta",
    "bree",
    "rod",
    "moose",
    "penelope",
    "limberg",
    "candi",
    "rizzo",
    "samson",
    "bettina",
    "bella",
    "spike",
    "tank",
    "renée",
    "merengue",
    "rhonda",
    "hornsby",
    "bertha",
    "bitty",
    "bubbles",
    "hippeux",
    "harry",
    "biff",
    "rocco",
    "marina",
    "octavian",
    "zucker",
    "reneigh",
    "annalise",
    "cleo",
    "colton",
    "peaches",
    "elmer",
    "victoria",
    "papi",
    "ed",
    "julian",
    "roscoe",
    "buck",
    "clyde",
    "winnie",
    "savannah",
    "cube",
    "friga",
    "hopper",
    "gwen",
    "tex",
    "boomer",
    "iggly",
    "puck",
    "roald",
    "aurora",
    "wade",
    "flo",
    "sprinkle",
    "bam",
    "deirdre",
    "lopez",
    "erik",
    "fauna",
    "beau",
    "bruce",
    "fuchsia",
    "diana",
    "zell",
    "baabara",
    "vesta",
    "dom",
    "eunice",
    "cashmere",
    "curlos",
    "muffy",
    "frita",
    "willow",
    "pietro",
    "stella",
    "timbra",
    "wendy",
    "boris",
    "pancetti",
    "chops",
    "rasher",
    "hugh",
    "kevin",
    "lucy",
    "truffles",
    "maggie",
    "agnes",
    "curly",
    "gala",
    "peggy",
    "cobb",
    "spork",
    "blanche",
    "flora",
    "cranston",
    "phil",
    "queenie",
    "julia",
    "sprocket",
    "phoebe",
    "gladys",
    "sandy",
    "kody",
    "stitches",
    "pudge",
    "bluebear",
    "cheri",
    "chester",
    "barold",
    "june",
    "olive",
    "murphy",
    "judy",
    "maple",
    "pekoe",
    "tammy",
    "poncho",
    "vladimir",
    "tybalt",
    "bianca",
    "rolf",
    "rowan",
    "claudia",
    "bangle",
    "leonardo",
    "jitters",
    "midge",
    "admiral",
    "anchovy",
    "piper",
    "jay",
    "jacob",
    "robin",
    "lucha",
    "sparro",
    "peck",
    "jacques",
    "twiggy",
    "freya",
    "fang",
    "audie",
    "whitney",
    "lobo",
    "skye",
    "chief",
    "dobie",
    "vivian",
    "wolfgang",
    "kyle",
    "chevre",
    "kidd",
    "gruff",
    "billy",
    "sherb",
    "pashmina",
    "velma",
    "nan",
];
